# numpy practice

In [1]:
import numpy as np

In [2]:
myarr = np.array([[25,36,12,95]], np.int64)

In [3]:
myarr

array([[25, 36, 12, 95]], dtype=int64)

In [4]:
myarr[0, 1]

36

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr[0, 1] = 41

In [7]:
myarr[0,1]

41

In [8]:
myarr

array([[25, 41, 12, 95]], dtype=int64)

# Array creation: Conversion from other python structures

In [9]:
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarr.dtype

dtype('int32')

In [12]:
listarr.shape

(3, 3)

In [13]:
listarr.size

9

In [14]:
np.array({10,11,12})

array({10, 11, 12}, dtype=object)

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.shape

(2, 5)

In [18]:
zeros.dtype

dtype('float64')

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace = np.linspace(1,5,8)

In [22]:
lspace

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [23]:
emp = np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 1.42417221e-306, 1.37961641e-306,
        6.23040033e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 1.86921143e-306,
        6.23061763e-307, 9.34608432e-307, 1.86921007e-306],
       [7.56596412e-307, 2.22520559e-306, 1.69119330e-306,
        8.45559303e-307, 8.06613465e-308, 6.89810244e-307],
       [1.22387550e-307, 2.22522596e-306, 8.34423917e-308,
        1.11261162e-306, 1.78021527e-306, 1.11260619e-306]])

In [25]:
emp_like = np.empty_like(lspace)

In [26]:
emp_like

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [27]:
ide = np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr = arr.reshape(3,33)

In [33]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr = arr.ravel()

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.shape

(99,)

In [37]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [38]:
ar = np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.sum(axis=0)

array([12,  8,  9])

In [41]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [42]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar.flat

In [44]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim

2

In [46]:
ar.size

9

In [47]:
ar.nbytes

36

In [48]:
one = np.array([1,2,5,66,48])

In [49]:
one.argmax()

3

In [50]:
one.argmin()

0

In [51]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [52]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [54]:
ar.argmin()

8

In [55]:
ar.argmax()

6

In [56]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [57]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [58]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [59]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [60]:
ar.ravel

<function ndarray.ravel>

In [61]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [62]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [63]:
ar.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
one

array([ 1,  2,  5, 66, 48])

In [66]:
ar2 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [67]:
ar + ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [68]:
ar * ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [69]:
ar.sum()

29

In [70]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [71]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [72]:
type(np.where(ar>5))

tuple

In [73]:
np.count_nonzero(ar)

8

In [74]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [75]:
import sys

In [76]:
py_ar = [12,15,88,56]

In [77]:
np_ar = np.array(py_ar)

In [78]:
sys.getsizeof(1) * len(py_ar)

112

In [79]:
np_ar.itemsize * np_ar.size

16

In [80]:
np_ar.tolist()

[12, 15, 88, 56]